/**
 * CreateTicketDialog Component
 * Allows Pro+ users to create Jira or Linear tickets for compliance issues
 */

'use client';

import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { toast } from 'sonner';
import { Ticket, ExternalLink } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

interface CreateTicketDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedResourceIds: string[];
  selectedResources?: any[];
}

type TicketPlatform = 'jira' | 'linear';
type TicketPriority = 'critical' | 'high' | 'medium' | 'low';

export function CreateTicketDialog({
  open,
  onOpenChange,
  selectedResourceIds,
  selectedResources = [],
}: CreateTicketDialogProps) {
  const [platform, setPlatform] = useState<TicketPlatform>('linear');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [priority, setPriority] = useState<TicketPriority>('high');
  const [assignee, setAssignee] = useState('');
  const [isCreating, setIsCreating] = useState(false);

  // Auto-generate title and description based on selected resources
  const generateTicketContent = () => {
    const criticalIssues = selectedResources.filter(
      r => r.compliance_issues?.some((i: any) => i.severity === 'critical')
    );
    const unencrypted = selectedResources.filter(r => !r.is_encrypted);
    const publicResources = selectedResources.filter(r => r.is_public);

    let autoTitle = '';
    let autoDescription = '';

    if (criticalIssues.length > 0) {
      autoTitle = `[URGENT] ${criticalIssues.length} critical compliance issue${criticalIssues.length !== 1 ? 's' : ''} detected`;
      autoDescription = `Critical compliance issues found in AWS resources:\n\n`;
    } else if (unencrypted.length > 0) {
      autoTitle = `${unencrypted.length} unencrypted AWS resource${unencrypted.length !== 1 ? 's' : ''} require attention`;
      autoDescription = `Unencrypted resources detected:\n\n`;
    } else if (publicResources.length > 0) {
      autoTitle = `${publicResources.length} publicly accessible resource${publicResources.length !== 1 ? 's' : ''} detected`;
      autoDescription = `Public resources that may pose security risk:\n\n`;
    } else {
      autoTitle = `AWS resource compliance review - ${selectedResourceIds.length} resource${selectedResourceIds.length !== 1 ? 's' : ''}`;
      autoDescription = `Resources requiring compliance review:\n\n`;
    }

    // Add resource details
    selectedResources.slice(0, 10).forEach((resource) => {
      autoDescription += `• ${resource.resource_name || resource.resource_id} (${resource.resource_type})\n`;
      autoDescription += `  Region: ${resource.region}\n`;
      if (!resource.is_encrypted) {
        autoDescription += `  ⚠️ Not encrypted\n`;
      }
      if (resource.is_public) {
        autoDescription += `  ⚠️ Publicly accessible\n`;
      }
      if (resource.compliance_issues?.length > 0) {
        autoDescription += `  ⚠️ ${resource.compliance_issues.length} compliance issue(s)\n`;
      }
      autoDescription += `\n`;
    });

    if (selectedResources.length > 10) {
      autoDescription += `\n... and ${selectedResources.length - 10} more resources\n`;
    }

    autoDescription += `\n---\nGenerated by DevControl AWS Resource Inventory`;

    setTitle(autoTitle);
    setDescription(autoDescription);
  };

  const handleCreate = async () => {
    if (!title.trim()) {
      toast.error('Please enter a ticket title');
      return;
    }

    setIsCreating(true);

    try {
      // Simulate ticket creation
      await new Promise(resolve => setTimeout(resolve, 1500));

      toast.success(`${platform === 'jira' ? 'Jira' : 'Linear'} ticket created`, {
        description: `${selectedResourceIds.length} resource${selectedResourceIds.length !== 1 ? 's' : ''} linked to ticket`,
      });

      onOpenChange(false);
      // Reset form
      setTitle('');
      setDescription('');
      setPriority('high');
      setAssignee('');
    } catch (error: any) {
      toast.error('Failed to create ticket', {
        description: error.message || 'Could not create ticket in external system',
      });
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="h-10 w-10 rounded-lg bg-indigo-100 dark:bg-indigo-900 flex items-center justify-center">
              <Ticket className="h-5 w-5 text-indigo-600 dark:text-indigo-400" />
            </div>
            <div>
              <DialogTitle>Create Ticket</DialogTitle>
              <DialogDescription>
                Create a ticket for {selectedResourceIds.length} selected resource{selectedResourceIds.length !== 1 ? 's' : ''}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Platform Selection */}
          <div className="space-y-3">
            <Label className="text-base font-semibold">Platform</Label>
            <RadioGroup value={platform} onValueChange={(value) => setPlatform(value as TicketPlatform)}>
              <div className="grid grid-cols-2 gap-4">
                <div
                  className={`flex items-start space-x-3 p-4 border rounded-lg cursor-pointer transition-colors ${
                    platform === 'jira'
                      ? 'border-primary bg-primary/5'
                      : 'border-border hover:border-primary/50'
                  }`}
                  onClick={() => setPlatform('jira')}
                >
                  <RadioGroupItem value="jira" id="jira" className="mt-1" />
                  <div className="flex-1">
                    <Label htmlFor="jira" className="font-medium cursor-pointer flex items-center gap-2">
                      Jira
                      <ExternalLink className="h-3 w-3" />
                    </Label>
                    <p className="text-xs text-muted-foreground mt-1">
                      Atlassian Jira Cloud
                    </p>
                  </div>
                </div>

                <div
                  className={`flex items-start space-x-3 p-4 border rounded-lg cursor-pointer transition-colors ${
                    platform === 'linear'
                      ? 'border-primary bg-primary/5'
                      : 'border-border hover:border-primary/50'
                  }`}
                  onClick={() => setPlatform('linear')}
                >
                  <RadioGroupItem value="linear" id="linear" className="mt-1" />
                  <div className="flex-1">
                    <Label htmlFor="linear" className="font-medium cursor-pointer flex items-center gap-2">
                      Linear
                      <ExternalLink className="h-3 w-3" />
                    </Label>
                    <p className="text-xs text-muted-foreground mt-1">
                      Modern issue tracking
                    </p>
                  </div>
                </div>
              </div>
            </RadioGroup>
          </div>

          {/* Auto-generate button */}
          <div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={generateTicketContent}
              className="w-full"
            >
              Auto-generate Title & Description
            </Button>
          </div>

          {/* Title */}
          <div className="space-y-2">
            <Label htmlFor="title">
              Title <span className="text-red-500">*</span>
            </Label>
            <Input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Brief description of the issue"
            />
          </div>

          {/* Description */}
          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Detailed information about the resources and required actions..."
              rows={8}
              className="font-mono text-sm"
            />
          </div>

          {/* Priority & Assignee */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="priority">Priority</Label>
              <Select value={priority} onValueChange={(value) => setPriority(value as TicketPriority)}>
                <SelectTrigger id="priority">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="critical">🔴 Critical</SelectItem>
                  <SelectItem value="high">🟠 High</SelectItem>
                  <SelectItem value="medium">🟡 Medium</SelectItem>
                  <SelectItem value="low">🟢 Low</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="assignee">Assignee (optional)</Label>
              <Input
                id="assignee"
                value={assignee}
                onChange={(e) => setAssignee(e.target.value)}
                placeholder="email@company.com"
              />
            </div>
          </div>

          {/* Resource Summary */}
          <div className="p-4 bg-muted/50 rounded-lg space-y-2">
            <div className="font-medium text-sm flex items-center justify-between">
              <span>Linked Resources</span>
              <Badge variant="secondary">{selectedResourceIds.length}</Badge>
            </div>
            <div className="text-xs text-muted-foreground">
              {selectedResources.slice(0, 3).map((resource: any) => (
                <div key={resource.id} className="truncate">
                  • {resource.resource_name || resource.resource_id}
                </div>
              ))}
              {selectedResources.length > 3 && (
                <div>+ {selectedResources.length - 3} more...</div>
              )}
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isCreating}>
            Cancel
          </Button>
          <Button onClick={handleCreate} disabled={isCreating || !title.trim()}>
            {isCreating ? 'Creating...' : `Create ${platform === 'jira' ? 'Jira' : 'Linear'} Ticket`}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
